services:
  n8n:
    image: n8nio/n8n:latest
    environment:
      - TZ=${TZ:-America/Sao_Paulo}
      - N8N_HOST=${SUBDOMAIN_N8N:-n8n}.${DOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN_N8N:-n8n}.${DOMAIN}/
      - GENERIC_TIMEZONE=${TZ:-America/Sao_Paulo}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/n8n:/home/node/.n8n
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        # HTTP
        - "traefik.http.routers.n8n.entrypoints=http"
        - "traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN_N8N:-n8n}.${DOMAIN}`)"
        - "traefik.http.routers.n8n.middlewares=n8n-https-redirect"
        # HTTPS
        - "traefik.http.routers.n8n-secure.entrypoints=https"
        - "traefik.http.routers.n8n-secure.rule=Host(`${SUBDOMAIN_N8N:-n8n}.${DOMAIN}`)"
        - "traefik.http.routers.n8n-secure.tls=true"
        - "traefik.http.routers.n8n-secure.tls.certresolver=cloudflare"
        - "traefik.http.routers.n8n-secure.service=n8n"
        # Middlewares
        - "traefik.http.middlewares.n8n-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.n8n-https-redirect.redirectscheme.permanent=true"
        # Service
        - "traefik.http.services.n8n.loadbalancer.server.port=5678"

networks:
  proxy:
    external: true
